services:
  - type: web
    name: backend-nassu
    runtime: node
    buildCommand: |
      cd backend
      npm install
      npm install -g typescript
      npm run build
    startCommand: node backend/dist/index.js
    envVars:
      - key: MONGODB_URI
        fromDatabase:
          name: mongodb
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true

  - type: web
    name: nassu-frontend
    runtime: static
    buildCommand: npm install --prefix frontend && npm run build --prefix frontend
    staticPublishPath: "./frontend/build"
    envVars:
      - key: REACT_APP_API_URL
        sync: false  # This will be set after backend is deployed
    autoDeploy: true

databases:
  - name: mongodb
    databaseName: nassu
    user: nassu_user
    plan: free
